### PR TITLE
Rabbit mq

### PR DESCRIPTION
**Pull request by barkhashah**
Merging RabbitMQ library, sample application and unit tests in the feature/dotnet

### CODE REVIEW

**Comment by niemyjski** [comment]
I'm going to merge this in, we may or may not keep the two sample applications. We'll have to think about it. Everything else looks good :) Thank you!!!!!!!!

**Comment by niemyjski** [comment]
Thank you for your contribution. It's greatly appreciated! Do you know if there is a good way to setup rabbit mq on appveyor so we can get the tests running?

**Comment by niemyjski** [comment]
I just found this https://gist.github.com/FeodorFitsner/06b377df42ba8f398909 looks like we just need to put that script in the tools folder and call it next to our appveyor script for installing redis.. Would you mind doing that?

**Comment by niemyjski** [comment]
I'll merge this in and install the script, will only take me a minute :)

**Comment by niemyjski** [comment]
Everything has been merged, tested and deployed Thanks a bunch! I had one last question...


```

        private void CloseConnection() {
            if (_publisherClient != null && _publisherClient.IsOpen)
                _publisherClient.Close();
            if (_subscriberClient != null && _subscriberClient.IsOpen)
                _subscriberClient.Close();

            if (_lock != null) {
                using (_lock.Lock())
                    _publisherChannel?.Abort();
            }

            _subscriberChannel?.Abort();
        }
```

Any reason for locking publisher channel? Why not the subscriber channel. I would of thought channels would need to be closed before clients... Is this correct? You are constructing the channels from the client but disposing of them the opposite way.

**Comment by barkhashah** [comment]
@niemyjski - Actually as per the RabbitMQ documentation, channel should not be shared across the threads. I only locked publisher channel because publishing messages from the multiple threads of the same process is very likely compared to subscribing the event on every thread. We subscribe only once , however, we can publish as many times on the same process. Please let me know if I am wrong in thinking here or suggest me if you see any other possibility where we can subscribe on the same channel on different threads.

>> I would of thought channels would need to be closed before clients... Is this correct?
I agree. Channel should be closed first and then client connections :+1: 
I will go ahead and make this change.

**Comment by ejsmith** [comment]
@barkhashah also, I noticed that Rabbit supports delayed messages. So we should use that instead of the timer based in memory delay since that has the potential to lose messages.

**Pull request merged**
